version: '3.8'

services:
  db:
    image: postgres:14
    container_name: tutor_virtual_db
    environment:
      POSTGRES_USER: tutor_admin
      POSTGRES_PASSWORD: yc30RkCrFc3x
      POSTGRES_DB: tutor_virtual
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tutor_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tutor.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: